# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Specwatch < Formula
  desc "Spec-driven architectural drift detector for the terminal"
  homepage "https://github.com/RajeshShrirao/Specwatch"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RajeshShrirao/Specwatch/releases/download/v0.1.0/specwatch_macOS_x86_64.tar.gz"
      sha256 "de85020832c9b2b05c0c69fc1cda3b4189eb96a686b73966f1b23599af380eea"

      define_method(:install) do
        bin.install "specwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RajeshShrirao/Specwatch/releases/download/v0.1.0/specwatch_macOS_arm64.tar.gz"
      sha256 "d1c73362b3856eff8f1dfc5e90c6797364ddb25ef5827da9724de02bc6cbbf23"

      define_method(:install) do
        bin.install "specwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RajeshShrirao/Specwatch/releases/download/v0.1.0/specwatch_Linux_x86_64.tar.gz"
      sha256 "23b22184cf0a43d793ff8a0d7a03537a8f21b14c42aa63763e5c3c43e6be747f"
      define_method(:install) do
        bin.install "specwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RajeshShrirao/Specwatch/releases/download/v0.1.0/specwatch_Linux_arm64.tar.gz"
      sha256 "ed816c5fc0f82e852697ec460f384b72966752ac30d7bdb6fd5b89bff72a2bba"
      define_method(:install) do
        bin.install "specwatch"
      end
    end
  end

  test do
    assert_match "specwatch version", shell_output("#{bin}/specwatch version")
  end
end
