# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Specwatch < Formula
  desc "Spec-driven architectural drift detector for the terminal"
  homepage "https://github.com/RajeshShrirao/Specwatch"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RajeshShrirao/Specwatch/releases/download/v0.1.1/specwatch_macOS_x86_64.tar.gz"
      sha256 "ee62b5e0bcaea02ee5d09a6268dfdc05434361274d6d47216299fb114a28118d"

      define_method(:install) do
        bin.install "specwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RajeshShrirao/Specwatch/releases/download/v0.1.1/specwatch_macOS_arm64.tar.gz"
      sha256 "57ead9cea326961f7944a28c6d0c2d179a1e8f575aaecb8781b67e1209d7ae6d"

      define_method(:install) do
        bin.install "specwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RajeshShrirao/Specwatch/releases/download/v0.1.1/specwatch_Linux_x86_64.tar.gz"
      sha256 "a2862931cd5de60787be00e6986e1fe9979b8601a1733c8f634ddb2b9aa11bf4"
      define_method(:install) do
        bin.install "specwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RajeshShrirao/Specwatch/releases/download/v0.1.1/specwatch_Linux_arm64.tar.gz"
      sha256 "2b70b0669b99f9e0a2931a97906851f1060556f1077726b50f2859e48bb64fe3"
      define_method(:install) do
        bin.install "specwatch"
      end
    end
  end

  test do
    assert_match "specwatch version", shell_output("#{bin}/specwatch version")
  end
end
